spring:
  kafka:
    bootstrap-servers: your-kafka-url-with:port
    client-id: eventhub-kafka-producer
#    For azure event-hub
    properties:
      sasl.jaas.config: your-sasl-config
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
    template:
      default-topic: topic-name
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        partitioner:
#          class: org.apache.kafka.clients.producer.RoundRobinPartitioner


